name: nlp_polarization
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.11 #maybe to update the cuml may use a older version (3.9Y)
  - numpy==1.24.4 #conflit with cuml
  - pandas
  - scikit-learn
  - nltk
  - pip
  - seaborn
  - matplotlib
  - torch
  - transformers
  - cudf==24.02
  - cupy==12.0
  - pip:
    - transformers
    - spacy==3.8.5


#python -m spacy download en_core_web_sm
#python -m nltk.downloader punkt
