name: spacy-gpu
channels:
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - spacy
  - spacy-transformers
  - transformers
  - sentencepiece
  - cupy

