name: rapids_nlp_env 
channels:
  - rapidsai 
  - nvidia 
  - conda-forge 
  - defaults 
dependencies:
  # --- Core Specifications ---
  - python=3.10
  - cudatoolkit=11.8

  - rapids=24.04

  # --- Standard Data Science & Utility Libraries from your imports ---
  - pandas
  - numpy
  - scikit-learn 
  - joblib
  - matplotlib 
  - seaborn
