# Unified Configuration File for Multiple Models

# --- Common Parameters ---
common:
  split_params:
    test_size: 0.15
    validation_size: 0.25
    random_state: 42
    seeds: [42, 123, 789] 

  data_params:
    congress_year_start: 76
    congress_year_end: 111 # is included

  party_map:
    D: 0 # Democrat
    R: 1 # Republican

# --- Common TF-IDF Settings and Tuning Grids (FOR FIXED VOCABULARY) ---
common_tfidf_config: &common_tfidf_config
  #tfidf_use_idf_grid: [True, False]
  tfidf_norm_grid: ['l1', 'l2'] # None means no normalization
  svm_class_weight_grid: [null, 'balanced'] #class wieght
  # tfidf_sublinear_tf_grid: [True, False]

# --- Model Specific Parameters and Tuning Grids ---

bayes:
  <<: *common_tfidf_config # Merges all keys from common_tfidf_config here
  # Bayes-specific parameters
  bayes_alpha_grid: [0.5, 1.0, 2.0]
  #already balance calss weght

svm:
  <<: *common_tfidf_config # Merges all keys from common_tfidf_config here
  # SVM-specific parameters
  C_grid: [0.1, 1, 10]
  max_iter: 10000

logistic_regression:
  <<: *common_tfidf_config # Merges all keys from common_tfidf_config here
  # Logistic Regression specific parameters
  lr_C_grid: [0.01, 0.1, 1.0]
  lr_max_iter_grid: [500] #100 iteration was too litle, 200, 1000 too many 
  lr_penalty_grid: ['l1', 'l2'] #before l2 was hard coded
  lr_class_weight_grid: [null, 'balanced'] #class wieght