model_name: svm
tfidf_max_features: 10000
ngram_range: [1, 2]

split_params:
  test_size: 0.15
  validation_size: 0.25
  random_state: 42
  seeds: [42, 43, 44]

data_params:
  congress_year_start: 76
  congress_year_end: 112

party_map:
  D: 0
  R: 1
  # Add other parties if necessary, they will be excluded if not in this map
